name: Hello Pipeline
on:
  push:

jobs:

  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo "Hello from GitHub Actions"
   
  test:
    needs: hello
    runs-on: ubuntu-latest
    
    steps:
      - name: Run test
        run: echo "Running tests"